version: '3.8'
services:
  api:
    image: luzinga-api
    build:
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:80
  db:
    image: luzinga-mssql
    build:
      context: ./.docker/db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HakunaM4t4t4@171
    ports:
      - "1433:1433"
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P HakunaM4t4t4@171 -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
