version: '3.8'

volumes:
  db_volume:

services:
  api:
    image: luzinga-api
    build:
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:80
  db:
    image: luzinga-mssqle
    build:
      context: ./.docker/db
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - db_volume
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
