version: '3.8'

volumes:
  db_volume:

services:
  api:
    image: luzinga-api
    build:
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:80
  db:
    image: luzinga-mssql
    build:
      context: ./.docker/db
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - /var/lib/redis:/data
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
  redis:
    image: redis:latest
    volumes:
      - redis_volume
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env
    command: ["redis-server","--save",
                              "60",
                              "1",
                              "--loglevel",
                              "warning",
                              "--requirepass",
                              "$REDIS_PASSWORD"]
